### ISSUE TITLE
Conflict with ScanSat

### ISSUE THREAD

**Issue by my-th-os** [allista/AutoLoadGame#10]
Having a fresh KSP 1.3.1 and a working ScanSat 18.4. Then installed AutoLoadGame 1.0.6 and ScanSats button disappeared. With blizzy's there is a button, but no GUI pops up. Both causing exceptions the log, see issue [issue #317](https://github.com/S-C-A-N/SCANsat/issues/317) reported to ScanSat. DMagic1 just says "Never skip the main menu. It will break any number of things."
Search in the forum shows some more mods where AutoLoadGame causes problems.
Is there any more convenient way to skip those tedious menu clicking?

**Comment by allista** [comment]
I've actually stopped public support of ALG precisely because there was a much better and user-friendly mod that does the same thing without such issues: https://forum.kerbalspaceprogram.com/index.php?/topic/85834-130-malahs-quick-mods-20170531/ (QuickStart one). But now I see that it's abandoned. A pity.

I myself continue to use it in development out of habit and for simplicity. So I'll check out the problem with ScanSat.

**Comment by allista** [comment]
I've released a new version that waits for 60 frames before leaving the MAINMENU.
https://spacedock.info/mod/832/AutoLoadGame
Could you please check if it solves the issue with ScanSat?

**Comment by mlheur** [comment]
FWIW, I'm using KSP 1.3.1 with ALG 1.0.7 and SCANsat 18.4; the buttons all work fine.
